# Ensure all fields are filled, then rename to "config.toml"

title = "Riffplayer Config"

[spotipy]
client_id = ""
client_secret = ""
redirect_uri = ""

[device]
default_device_id = ""
target_device_id = ""